# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Deploy manually'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build WebSite
      run: swift run
    - name: Set Public Folder
      run: |
        mkdir .public 
        cp -r Output/* .public 
        mv .public public
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: main
        folder: public
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}      
