name: Swift

on:
  push:
    branches: [ authoring ]
  pull_request:
    branches: [ authoring ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
