name: Swift

on:
  push:
    branches: [ authoring ]
  pull_request:
    branches: [ authoring ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Build WebSite
      run: swift run
    - name: Set Public Folder
        run: |
            mkdir .public
            cp -r Output/* .public
            mv .public public
    - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: public
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}      
